### ISSUE TITLE
Animation freezes and phone rotation doesn't work as expected

### ISSUE THREAD

**Issue by socksrust** [guilhermepontes/guilhermepontes.github.io#1]
![screen shot 2018-09-06 at 20 58 24](https://user-images.githubusercontent.com/13947203/45191120-d0179b00-b217-11e8-83ce-41d91c421328.png)
![screen shot 2018-09-06 at 20 58 34](https://user-images.githubusercontent.com/13947203/45191123-d0b03180-b217-11e8-8cb6-1f900ea41f87.png)

**Comment by guilhermepontes** [comment]
This was.. unexpected! Thanks @jaburcodes ❤️

**Comment by socksrust** [comment]
Glad to help o/ <3
